# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Linux CPU Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-unit-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: 'true'
    - run: git submodule sync --recursive
    - run: git submodule update --init --recursive --force
    - run: git submodule foreach --recursive
    - run: git lfs ls-files
    - run: git lfs pull
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore /p:Configuration=Linux-CPU-Debug /p:Platform="Any CPU"
    - name: BuildCSharpTemplatesTool
      run: dotnet build --configuration Release csharp-templates/CSharpTemplates/
    - name: debugging
      run: ls /home/runner/work/flip-proof/flip-proof/FlipProof.Torch//../csharp-templates/CSharpTemplates/bin/Release/net8.0/
    - name: Build
      run: dotnet build --configuration Linux-CPU-Debug --no-restore
    - name: Test
      run: dotnet test --configuration Linux-CPU-Debug --no-build --verbosity normal